name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base-jammy
    steps:
      - uses: actions/checkout@v4

      - name: Build and Test
        run: |
          . /opt/ros/humble/setup.sh
          colcon build --symlink-install
          colcon test
          colcon test-result --verbose

          colcon test-result --verbose

      - name: Run functional test
        run: |
          . /opt/ros/humble/setup.sh
          source install/setup.bash
          ./test/test.bash $(pwd)
