name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base-jammy
    steps:
      - uses: actions/checkout@v3
      - name: build and test
        run: |
          rsync -av ./ /root/src/
          cd /root
          . /opt/ros/humble/setup.sh
          rosdep update
          rosdep install -i --from-path src --rosdistro humble -y
          colcon build --symlink-install
          colcon test
          colcon test-result
